<a href="https://colab.research.google.com/github/SrimantaSingha/sentiment_analysis/blob/main/Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import os

# Import functions for data preprocessing & data preparation
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample
from sklearn.feature_extraction.text import CountVectorizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer

from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer, LancasterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.corpus import stopwords
from nltk.corpus import wordnet
import string
from string import punctuation
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
import re

In [ ]:
data = pd.read_csv('YouTube_comments(wahed).csv')
data.columns
data1=data.drop(['Unnamed: 0','Likes','Time','user','UserLink'],axis=1)
data1

Comment
0    Play on  with a super powerful processor and s...
1    Ok this is awesome. Im so happy that Samsung i...
2    Ever since the S22 Ultra, I've been the bigges...
3    By far the most creative and captivating intro...
4    Probably one of the best smartphone trailers E...
..                                                 ...
815                          Samsung is always amazing
816                  But i phone is dream for everyone
817  Whatever they produce, after 2 years you have ...
818       I would hate to drop this phone on the floor
819                          My Phone Is Samsung  A10s

[820 rows x 1 columns]

In [ ]:
nltk.download('vader_lexicon')
sentiments = SentimentIntensityAnalyzer()
data1["Positive"] = [sentiments.polarity_scores(i)["pos"] for i in data1["Comment"]]
data1["Negative"] = [sentiments.polarity_scores(i)["neg"] for i in data1["Comment"]]
data1["Neutral"] = [sentiments.polarity_scores(i)["neu"] for i in data1["Comment"]]
data1['Compound'] = [sentiments.polarity_scores(i)["compound"] for i in data1["Comment"]]
score = data1["Compound"].values
sentiment = []
for i in score:
    if i >= 0.05 :
        sentiment.append('Positive')
    elif i <= -0.05 :
        sentiment.append('Negative')
    else:
        sentiment.append('Neutral')
data1["Sentiment"] = sentiment
data1.head()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


Comment  Positive  Negative  \
0  Play on  with a super powerful processor and s...     0.349     0.000   
1  Ok this is awesome. Im so happy that Samsung i...     0.358     0.018   
2  Ever since the S22 Ultra, I've been the bigges...     0.259     0.000   
3  By far the most creative and captivating intro...     0.189     0.000   
4  Probably one of the best smartphone trailers E...     0.321     0.000   

   Neutral  Compound Sentiment  
0    0.651    0.8442  Positive  
1    0.624    0.9735  Positive  
2    0.741    0.9059  Positive  
3    0.811    0.5400  Positive  
4    0.679    0.7955  Positive

In [ ]:
data2=data1.drop(['Positive','Negative','Neutral','Compound'],axis=1)
data2.head()

Comment Sentiment
0  Play on  with a super powerful processor and s...  Positive
1  Ok this is awesome. Im so happy that Samsung i...  Positive
2  Ever since the S22 Ultra, I've been the bigges...  Positive
3  By far the most creative and captivating intro...  Positive
4  Probably one of the best smartphone trailers E...  Positive

In [ ]:
stop_words = stopwords.words('english')
porter_stemmer = PorterStemmer()
lancaster_stemmer = LancasterStemmer()
snowball_stemer = SnowballStemmer(language="english")
lzr = WordNetLemmatizer()

In [ ]:
def text_processing(text):
    # convert text into lowercase
    text = text.lower()

    # remove new line characters in text
    text = re.sub(r'\n',' ', text)

    # remove punctuations from text
    text = re.sub('[%s]' % re.escape(punctuation), "", text)

    # remove references and hashtags from text
    text = re.sub("^a-zA-Z0-9$,.", "", text)

    # remove multiple spaces from text
    text = re.sub(r'\s+', ' ', text, flags=re.I)

    # remove special characters from text
    text = re.sub(r'\W', ' ', text)

    #text = ' '.join([word for word in word_tokenize(text) if word not in stop_words])

    # stemming using porter stemmer from nltk package - msh a7sn 7aga - momken: lancaster, snowball
    # text=' '.join([porter_stemmer.stem(word) for word in word_tokenize(text)])
    # text=' '.join([lancaster_stemmer.stem(word) for word in word_tokenize(text)])
    # text=' '.join([snowball_stemer.stem(word) for word in word_tokenize(text)])

    # lemmatizer using WordNetLemmatizer from nltk package
    text=' '.join([lzr.lemmatize(word) for word in word_tokenize(text)])

    return text

In [ ]:
nltk.download('omw-1.4')
data_copy = data2.copy()
data_copy.Comment = data_copy.Comment.apply(lambda text: text_processing(text))

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


In [ ]:
le = LabelEncoder()
data_copy['Sentiment'] = le.fit_transform(data_copy['Sentiment'])

In [ ]:
processed_data = {
    'Sentence':data_copy.Comment,
    'Sentiment':data_copy['Sentiment']
}

processed_data = pd.DataFrame(processed_data)
processed_data.head()

Sentence  Sentiment
0  play on with a super powerful processor and sn...          2
1  ok this is awesome im so happy that samsung is...          2
2  ever since the s22 ultra ive been the biggest ...          2
3  by far the most creative and captivating intro...          2
4  probably one of the best smartphone trailer ev...          2

In [ ]:
processed_data['Sentence']

0      play on with a super powerful processor and sn...
1      ok this is awesome im so happy that samsung is...
2      ever since the s22 ultra ive been the biggest ...
3      by far the most creative and captivating intro...
4      probably one of the best smartphone trailer ev...
                             ...                        
815                            samsung is always amazing
816                    but i phone is dream for everyone
817    whatever they produce after 2 year you have to...
818         i would hate to drop this phone on the floor
819                             my phone is samsung a10s
Name: Sentence, Length: 820, dtype: object

In [ ]:
processed_data.tail()

Sentence  Sentiment
815                          samsung is always amazing          2
816                  but i phone is dream for everyone          2
817  whatever they produce after 2 year you have to...          2
818       i would hate to drop this phone on the floor          0
819                           my phone is samsung a10s          1

In [ ]:
processed_data['Sentiment'].value_counts()

2    532
1    212
0     76
Name: Sentiment, dtype: int64

In [ ]:
NegCom = processed_data.Sentence[processed_data["Sentiment"]==0]

In [ ]:
neg_comments=[]
for n in NegCom:
   neg_comments.append(n)
pd.DataFrame({"Negative Comments":neg_comments})


Negative Comments
0   hmmm still not convincing me enough to move fr...
1   samsung official introduction are not a good a...
2        the dumb equipment of 700 performance better
3                    galaxy m13 is bad at performance
4                         it the worst that can exist
..                                                ...
71  dumbest commercial ever my god that wa painful...
72  cool and all but they bragged how fast the 22 ...
73  samsung just stick to one phone for atleast 2 ...
74                                             boring
75       i would hate to drop this phone on the floor

[76 rows x 1 columns]

In [ ]:
df_neutral = processed_data[(processed_data['Sentiment']==1)]
df_negative = processed_data[(processed_data['Sentiment']==0)]
df_positive = processed_data[(processed_data['Sentiment']==2)]

# upsample minority classes
df_negative_upsampled = resample(df_negative,
                                 replace=True,
                                 n_samples= 532,
                                 random_state=42)

df_neutral_upsampled = resample(df_neutral,
                                 replace=True,
                                 n_samples= 532,
                                 random_state=42)


# Concatenate the upsampled dataframes with the neutral dataframe
final_data = pd.concat([df_negative_upsampled,df_neutral_upsampled,df_positive])

In [ ]:
final_data['Sentiment'].value_counts()

0    532
1    532
2    532
Name: Sentiment, dtype: int64

In [ ]:
final_data.tail()

Sentence  Sentiment
812  bring s pen in budget like note 10 lite at lea...          2
813                     nothing new but nice marketing          2
815                          samsung is always amazing          2
816                  but i phone is dream for everyone          2
817  whatever they produce after 2 year you have to...          2

In [ ]:
corpus = []
for sentence in final_data['Sentence']:
    corpus.append(sentence)
corpus[0:5]

['literally the worst phone ad ever',
 'samsung never disappoints stunning phone again',
 'dumbest commercial ever my god that wa painful to watch',
 'i have samsung note 9every time i do software update the screen turn yellowish which wa the case with most of the note 9 device last time it happened i had to use my sister verified account to tweet and get it repaired which wa a long procedure for something that i didnt even do cause even after agreeing of this issue from their end samsung yet deny for the repair now it happened again and i dont know what to do not a happy customer',
 'bro said thank you and died']

In [ ]:
corpus[1595]

'whatever they produce after 2 year you have to visit service center to change display and they will charge 12 of the original phone price enjoy'

In [ ]:
c=corpus
len(c)

1596

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()
y = final_data.iloc[:, -1].values

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
np.shape(X)

(1596, 1500)

In [ ]:
for k in X[1595]:
    if k!=0:
       print(k)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
1
1
1
1
1


## **Gaussian Naive Bayes:**

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

array([[150,   5,   4],
       [  0, 147,   8],
       [ 13,   6, 146]])

In [ ]:
nb_score = accuracy_score(y_test, y_pred)
print('accuracy',nb_score)

accuracy 0.9248434237995825


## **Random Forest:**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(criterion='gini',random_state=0)
forest.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [ ]:
y_pred = forest.predict(X_test)
cm=confusion_matrix(y_test,y_pred)
cm

array([[155,   0,   4],
       [  0, 154,   1],
       [  5,  25, 135]])

In [ ]:
forest_score=accuracy_score(y_test,y_pred)
print('accuracy:',forest_score)

accuracy: 0.9269311064718163


## **Support Vector Machine:**

In [ ]:
from sklearn.svm import SVC
kernel=["linear","rbf","poly"]
best_accuracy=0
for k in kernel:
    svc_model = SVC(kernel=k)
    svc_model.fit(X_train, y_train)
    y_pred = svc_model.predict(X_test)
    accuracy=accuracy_score(y_pred,y_test)
    if accuracy>best_accuracy:
       best_accuracy=accuracy
       best_kernel=k
print(f"Best accuracy is {best_accuracy} with best kernel is {best_kernel}")


Best accuracy is 0.918580375782881 with best kernel is linear


In [ ]:
svm_score=best_accuracy
svm_score

0.918580375782881

## **Accuracy score with different mode:**

In [ ]:
model=["Gaussian Naive Bayes","Random Forest","SVM"];accuracy=[]
accuracy=[nb_score,forest_score,svm_score]
pd.DataFrame({"Model":model,"Acuuracy":accuracy})

Model  Acuuracy
0  Gaussian Naive Bayes  0.924843
1         Random Forest  0.926931
2                   SVM  0.918580

## As we see that Random Forest is the highest accuracy model, we will use this model to classify new comments.

## **Classify new comments:**

In [ ]:
corpus_copy=[]
for sentence in final_data['Sentence']:
    corpus_copy.append(sentence)

In [ ]:
len(corpus_copy)

1596

In [ ]:
bag_of_words=corpus_copy

In [ ]:
bag_of_words.append("worst phone")
corpus_new=bag_of_words

In [ ]:
len(corpus_new)

1597

In [ ]:
corpus_new[1596]

'worst phone'

In [ ]:
X_new= cv.fit_transform(corpus_new).toarray()
X_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
np.shape(X_new)  # Dimensions of new input matrix.

(1597, 1500)

In [ ]:
test_new=X_new[1596]
test_new=np.reshape(test_new, (-1, 1500)) # where -1 infers the size of the new dimension from the size of the input array.
test_new # This is the numerical form(array) of the corresponding to new text data.

array([[0, 0, 0, ..., 0, 0, 0]])

In [ ]:
np.shape(test_new)

(1, 1500)

In [ ]:
for k in test_new[0]:
    if k!=0:
       print(k)

1
1


In [ ]:
y_pred = classifier.predict(test_new)
y_pred

array([0])

In [ ]:
y_pred = forest.predict(test_new)
y_pred

array([0])

## **Prediction function:**

In [ ]:
def new_text_prediction(text):
    corpus_copy=[]
    for sentence in final_data['Sentence']:
        corpus_copy.append(sentence)
  #  print(corpus_copy[len(corpus_copy)-1])
  #  print(len(corpus_copy))
    bag_of_words=corpus_copy
    bag_of_words.append(text)
    corpus_new=bag_of_words
  #  print(len(corpus_new))
  #  print(corpus_new[len(corpus_new)-1])
    X_new= cv.fit_transform(corpus_new).toarray()
    test_new=X_new[1596]
    test_new=np.reshape(test_new, (-1, 1500)) # where -1 infers the size of the new dimension from the size of the input array.
    # This is the numerical form(array) of the corresponding to new text data.
    y_pred = forest.predict(test_new)
  #  print(y_pred)
    if y_pred==[2]:
       print("This is a positive feedback")
    if y_pred==[0]:
       print("This is a negative feedback")
    if y_pred==[1]:
       print("This is a neutral feedback")


In [ ]:
new_text_prediction(" its okk")

This is a neutral feedback


In [ ]:
new_text_prediction("wonderful phone, i have never seen this before")

This is a positive feedback


In [ ]:
new_text_prediction("nothing new")


This is a neutral feedback


In [ ]:
new_text_prediction("bad one")

This is a negative feedback


In [2]:
pwd


'/content'